name: test ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  tidb510:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    services:
      tidb:
        image: hooopo/tind:v5.1.0
        options: --entrypoint /entrypoint.sh
        env:
          TIDB_VERSION: v5.1.0
        ports: ["4000:4000"]
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: sleep 3 && mysql --comments --host 127.0.0.1 --port 4000 -u root --password='' -e 'show databases;'
    - run: sleep 3 && mysql --comments --host 127.0.0.1 --port 4000 -u root --password='' -e 'create database t;'
